#!/usr/bin/env python3
"""Render hybrid event metadata and operator-facing docs from one registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[3]
REGISTRY_PATH = REPO_ROOT / "log-model/contracts/hybrid-event/projection-registry.v1.json"
OUTPUTS = {
    "metadata": REPO_ROOT / "log-model/contracts/hybrid-event/table-metadata.v1.json",
    "fields": REPO_ROOT / "log-model/docs/hybrid/SDM2.0-hybrid-event-field-standard.md",
    "projections": REPO_ROOT / "log-model/docs/hybrid/hybrid_event_projection.md",
    "routine_load": REPO_ROOT / "log-model/docs/hybrid/hybrid_event_routine_load.md",
    "api": REPO_ROOT / "log-model/docs/hybrid/hybrid_event_api_field_mapping.md",
}
HEADER = "<!-- Generated by log-model/contracts/scripts/render_hybrid_event_assets.py. Do not edit manually. -->\n\n"



def load_registry() -> dict[str, Any]:
    return json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))


def render_assets(registry: dict[str, Any]) -> dict[str, str]:
    metadata = {
        "metadata_version": 1,
        "source_registry": str(REGISTRY_PATH.relative_to(REPO_ROOT)),
        "registry_version": registry["registry_version"],
        "schema_version": registry["schema_version"],
        "projection_version": registry["projection_version"],
        "target_table": registry["target_table"],
        "key_columns": ["tenant_id", "occur_time", "event_id"],
        "columns": registry["columns"],
        "variant_objects": registry["variant_objects"],
        "aliases": registry["aliases"],
        "limits_bytes": registry["limits_bytes"],
    }
    return {
        "metadata": json.dumps(metadata, ensure_ascii=False, indent=2) + "\n",
        "fields": _field_standard(registry),
        "projections": _projection_doc(registry),
        "routine_load": _routine_load_doc(registry),
        "api": _api_doc(registry),
    }


def _field_standard(registry: dict[str, Any]) -> str:
    lines = [
        HEADER + "# SDM2.0 Hybrid Event Field Standard",
        "",
        f"Normative source: `{REGISTRY_PATH.relative_to(REPO_ROOT)}`.",
        "",
        "| Column | Logical path | Doris type | Projection | Access |",
        "|---|---|---|---|---|",
    ]
    for item in registry["columns"]:
        lines.append(
            f"| `{item['column']}` | `{item['path']}` | `{item['type']}` | "
            f"`{item['projection']}` | {', '.join(item['access'])} |"
        )
    for logical, meta in registry["variant_objects"].items():
        lines.append(f"| `{meta['physical_column']}` | `{logical}` | `VARIANT` | `CANONICAL_OBJECT` | DETAIL |")
    lines.extend(["", "Legacy aliases are read-only and MUST NOT appear in ingestion mappings.", ""])
    return "\n".join(lines)


def _projection_doc(registry: dict[str, Any]) -> str:
    defaults = registry["projection_rules"]["defaults"]
    overrides = registry["projection_rules"]["by_column"]
    lines = [
        HEADER + "# Hybrid Event Projection Contract",
        "",
        f"Projection version: `{registry['projection_version']}`.",
        "",
        "| Logical path | Column | Type | Normalizer | Primary selection |",
        "|---|---|---|---|---|",
    ]
    for item in registry["columns"]:
        if not item["path"].startswith(("roles.", "facets.", "source_finding.")):
            continue
        rule = {**defaults, **overrides.get(item["column"], {})}
        lines.append(
            f"| `{item['path']}` | `{item['column']}` | `{item['projection']}` | "
            f"`{rule['normalizer']}` | `{rule['primary_selection'] or '-'}` |"
        )
    lines.extend([
        "",
        "`PRIMARY_ONLY` columns are list and filter accelerators. Arbitrary member search uses posting or relation tables.",
        "",
    ])
    return "\n".join(lines)


def _routine_load_doc(registry: dict[str, Any]) -> str:
    writable = [item["column"] for item in registry["columns"]] + [m["physical_column"] for m in registry["variant_objects"].values()]
    aliases = [item["legacy_column"] for item in registry["aliases"]]
    return "\n".join([
        HEADER + "# Hybrid Event Routine Load Contract",
        "",
        f"Target: `{registry['target_table']}`; projection version: `{registry['projection_version']}`.",
        "",
        "Routine Load writes only these canonical fields:",
        "",
        ", ".join(f"`{name}`" for name in writable),
        "",
        "The following compatibility aliases are forbidden write inputs:",
        "",
        ", ".join(f"`{name}`" for name in aliases),
        "",
        "During migration, current and target outputs are derived from the same logical event. Kafka source fields are not mapped independently into alias columns.",
        "",
    ])


def _api_doc(registry: dict[str, Any]) -> str:
    lines = [
        HEADER + "# Hybrid Event API Field Mapping",
        "",
        "The logical-event API assembles `metadata` and `event` from scalar columns and returns the four canonical objects unchanged.",
        "",
        "| API path | Storage source |",
        "|---|---|",
    ]
    for item in registry["columns"]:
        if item["path"].startswith(("metadata.", "event.")) or item["path"] == "schema_version":
            lines.append(f"| `{item['path']}` | `{item['column']}` |")
    for logical, meta in registry["variant_objects"].items():
        lines.append(f"| `{logical}` | `{meta['physical_column']}` |")
    lines.extend(["", "## Deprecated Compatibility Fields", "", "| Legacy field | Replacement |", "|---|---|"])
    for alias in registry["aliases"]:
        lines.append(f"| `{alias['legacy_column']}` | `{alias['target_column']}` |")
    lines.extend([
        "| `carrier` | `roles.carriers[]` |",
        "| `source_alert` | `source_finding` |",
        "",
        "The API reads `sdm_event` by default (`S4_EVENT_READ_TABLE=sdm_event_read` for the staged compat view).",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated assets are stale.")
    args = parser.parse_args()
    rendered = render_assets(load_registry())
    stale = []
    for key, path in OUTPUTS.items():
        content = rendered[key]
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(REPO_ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        raise SystemExit("stale generated hybrid assets: " + ", ".join(stale))


if __name__ == "__main__":
    main()
