#!/usr/bin/env python3
"""Historical hybrid-v1 sdm_event DDL renderer. Production channel retired.

007/026 were removed from the apply pipeline after behavior cutover.
`--check` succeeds only when those files are absent. Unadorned invocation
refuses to write them back.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "contracts/hybrid-event/projection-registry.v1.json"
TABLE_SQL = ROOT / "schema/007_sdm_event.sql"
ROUTINE_LOAD_SQL = ROOT / "schema/026_routine_load_sdm_event.sql"

DATABASE = "__DORIS_DB__"
TABLE = "sdm_event"
JOB = "sdm_events_load_hybrid_v1"
BUCKETS = 16
REPLICATION_NUM = 1
PARTITION_END = 3
DYNAMIC_PARTITION_START = "__DYNAMIC_PARTITION_START__"
HISTORY_PARTITION_NUM = "__HISTORY_PARTITION_NUM__"

DATETIME_COLUMNS = ("occur_time", "ingest_time", "parse_time")
INVERTED_INDEXES = (
    "record_kind",
    "event_domain",
    "event_type",
    "operation",
    "outcome",
    "severity",
    "source_ip",
    "target_ip",
    "source_user",
    "target_user",
    "target_domain",
    "observer_product",
    "network_protocol",
    "network_direction",
    "http_method",
    "http_status",
    "source_finding_severity",
    "source_finding_category",
    "source_finding_signature_id",
    "source_finding_action",
)
BLOOM_FILTER_COLUMNS = ("tenant_id", "event_id")

HEADER = (
    "-- Generated by log-model/scripts/generate_sdm_event_ddl.py. Do not edit manually.\n"
    "-- Source: log-model/contracts/hybrid-event/projection-registry.v1.json (hybrid-v1).\n"
    "-- Production table name is sdm_event; registry target_table sdm_event_target is the shadow name.\n"
)


def quote_identifier(value: str) -> str:
    return f"`{value.replace('`', '``')}`"


def escape_comment(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "''")


def load_registry() -> dict:
    return json.loads(REGISTRY.read_text(encoding="utf-8"))


def column_nullability(registry: dict) -> dict[str, bool]:
    defaults = registry["projection_rules"]["defaults"]
    overrides = registry["projection_rules"]["by_column"]
    nullable = {}
    for entry in registry["columns"]:
        rule = {**defaults, **overrides.get(entry["column"], {})}
        nullable[entry["column"]] = bool(rule["nullable"])
    return nullable


def physical_columns(registry: dict) -> list[tuple[str, str, bool, str]]:
    nullable = column_nullability(registry)
    columns: list[tuple[str, str, bool, str]] = []
    for entry in registry["columns"]:
        name = entry["column"]
        comment = f"投影自 {entry['path']}；{entry['projection']}"
        columns.append((name, entry["type"], nullable[name], comment))
    object_nulls = {
        "roles_obj": False,
        "facets_obj": False,
        "source_finding_obj": True,
        "extensions_obj": False,
    }
    for logical, meta in registry["variant_objects"].items():
        physical = meta["physical_column"]
        comment = f"权威逻辑对象 {logical}；完整结构见逻辑 Schema"
        columns.append((physical, "VARIANT", object_nulls[physical], comment))
    return columns


def unix_to_datetime(src: str) -> str:
    return (
        f"FROM_UNIXTIME(IF(CAST({src} AS DOUBLE) >= 100000000000, "
        f"CAST({src} AS DOUBLE) / 1000, CAST({src} AS DOUBLE)))"
    )


def render_table_sql(registry: dict) -> str:
    columns = physical_columns(registry)
    names = {name for name, *_ in columns}
    missing = [column for column in BLOOM_FILTER_COLUMNS + INVERTED_INDEXES if column not in names]
    if missing:
        raise SystemExit(f"index columns missing from registry: {missing}")

    lines = []
    for name, data_type, nullable, comment in columns:
        null_sql = "NULL" if nullable else "NOT NULL"
        lines.append(
            f"    {quote_identifier(name)} {data_type} {null_sql} COMMENT '{escape_comment(comment)}'"
        )
    for column in INVERTED_INDEXES:
        lines.append(
            f"    INDEX {quote_identifier('idx_' + column)} ({quote_identifier(column)}) "
            f"USING INVERTED COMMENT '{escape_comment(column + ' 过滤')}'"
        )

    properties = [
        '"enable_unique_key_merge_on_write" = "true"',
        f'"replication_num" = "{REPLICATION_NUM}"',
        '"dynamic_partition.enable" = "true"',
        '"dynamic_partition.time_unit" = "DAY"',
        f'"dynamic_partition.start" = "{DYNAMIC_PARTITION_START}"',
        f'"dynamic_partition.end" = "{PARTITION_END}"',
        '"dynamic_partition.prefix" = "p"',
        f'"dynamic_partition.buckets" = "{BUCKETS}"',
        '"dynamic_partition.create_history_partition" = "true"',
        f'"dynamic_partition.history_partition_num" = "{HISTORY_PARTITION_NUM}"',
        f'"bloom_filter_columns" = "{",".join(BLOOM_FILTER_COLUMNS)}"',
        '"storage_format" = "V3"',
        '"inverted_index_storage_format" = "V3"',
        '"light_schema_change" = "true"',
    ]
    return (
        HEADER
        + "-- 身份与 raw_log 同构：UNIQUE KEY / HASH / 分区策略一致。replication_num 与 006_raw_log.sql 对齐，HA 时两表一起改。\n"
        + "-- dynamic_partition.start / history_partition_num 由 apply 脚本按 DORIS_RETENTION_DAYS 替换，默认 7 天。\n"
        + f"CREATE TABLE IF NOT EXISTS {quote_identifier(DATABASE)}.{quote_identifier(TABLE)} (\n"
        + ",\n".join(lines)
        + "\n)\n"
        + "UNIQUE KEY(`tenant_id`, `occur_time`, `event_id`)\n"
        + "PARTITION BY RANGE(`occur_time`) ()\n"
        + f"DISTRIBUTED BY HASH(`tenant_id`, `event_id`) BUCKETS {BUCKETS}\n"
        + "PROPERTIES (\n    "
        + ",\n    ".join(properties)
        + "\n);\n"
    )


def render_routine_load_sql(registry: dict) -> str:
    columns = physical_columns(registry)
    staging = []
    expressions = []
    jsonpaths = []
    for name, data_type, _nullable, _comment in columns:
        jsonpaths.append(f"$.{name}")
        if name in ("tenant_id", "event_id"):
            staging.append(f"{name}_raw")
            expressions.append(f"{name} = TRIM({name}_raw)")
        elif name in DATETIME_COLUMNS:
            staging.append(f"{name}_ms")
            converted = unix_to_datetime(f"{name}_ms")
            if name == "occur_time":
                expressions.append(f"{name} = {converted}")
            else:
                expressions.append(f"{name} = IF({name}_ms IS NULL, NOW(3), {converted})")
        else:
            staging.append(name)

    col_sql = ",\n    ".join(staging + expressions)
    jsonpaths_sql = json.dumps(jsonpaths, separators=(",", ":"))
    return (
        HEADER
        + "-- Kafka hybrid-v1 -> sdm_event。jsonpaths 使用 Kafka 物理字段名（roles_obj 等）。\n"
        + "-- Placeholders: __DORIS_DB__ __KAFKA_BROKERS__ __KAFKA_TOPIC__ __KAFKA_OFFSETS__\n"
        + "-- 禁止写入兼容别名。首次生产用 OFFSET_END。\n"
        + f"USE {DATABASE};\n\n"
        + f"CREATE ROUTINE LOAD {JOB}\n"
        + f"ON {TABLE}\n"
        + "COLUMNS(\n    "
        + col_sql
        + "\n)\n"
        + "PROPERTIES (\n"
        + '    "format" = "json",\n'
        + f'    "jsonpaths" = \'{jsonpaths_sql}\',\n'
        + '    "strip_outer_array" = "false",\n'
        + '    "max_filter_ratio" = "1",\n'
        + '    "max_error_number" = "1000000000",\n'
        + '    "timezone" = "Etc/UTC"\n'
        + ")\n"
        + "FROM KAFKA (\n"
        + '    "kafka_broker_list" = "__KAFKA_BROKERS__",\n'
        + '    "kafka_topic" = "__KAFKA_TOPIC__",\n'
        + '    "kafka_partitions" = "__KAFKA_PARTITIONS__",\n'
        + '    "kafka_offsets" = "__KAFKA_OFFSETS__"\n'
        + ");\n"
    )


def generated_files(registry: dict) -> dict[Path, str]:
    return {
        TABLE_SQL: render_table_sql(registry),
        ROUTINE_LOAD_SQL: render_routine_load_sql(registry),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="succeed only when retired 007/026 files are absent",
    )
    args = parser.parse_args()
    retired = (TABLE_SQL, ROUTINE_LOAD_SQL)
    present = [str(path.relative_to(ROOT.parent)) for path in retired if path.exists()]
    if args.check:
        if present:
            print("retired hybrid DDL still present: " + ", ".join(present))
            return 1
        print("hybrid DDL retired (007/026 absent)")
        return 0
    print(
        "refusing to write 007/026: hybrid-v1 sdm_event channel retired; "
        "ingest is sdm_event_behavior (031/032)"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
